System Monitor: include/disk.h File Reference
disk.h File Reference
Disk monitoring functionality.
Data Structures
struct DiskInfo
Structure to hold all disk statistics.
struct DiskStats
Structure to hold disk partition information.
Macros
#define MAX_DISK_NAME 32
#define MAX_DISKS 8
#define MAX_MOUNT_PATH 256
Functions
void cleanup_disk_monitor (void)
Clean up disk monitoring resources.
int init_disk_monitor (void)
Initialize disk monitoring.
int update_disk_stats (DiskInfo *stats)
Update disk statistics.
Detailed Description
Disk monitoring functionality.
Definition in file disk.h.
Macro Definition Documentation
MAX_DISK_NAME
#define MAX_DISK_NAME 32
Definition at line 10 of file disk.h.
MAX_DISKS
#define MAX_DISKS 8
Definition at line 9 of file disk.h.
MAX_MOUNT_PATH
#define MAX_MOUNT_PATH 256
Definition at line 11 of file disk.h.
Function Documentation
cleanup_disk_monitor()
void cleanup_disk_monitor (void)
Clean up disk monitoring resources.
Definition at line 155 of file disk.c.
Referenced by main().
init_disk_monitor()
int init_disk_monitor (void)
Initialize disk monitoring.
Returns
0 on success, -1 on failure
Definition at line 92 of file disk.c.
References prev_reads, and prev_writes.
Referenced by main().
update_disk_stats()
int update_disk_stats (DiskInfo * stats)
Update disk statistics.
Parameters
stats Pointer to DiskInfo structure to update
Returns
0 on success, -1 on failure
Definition at line 98 of file disk.c.
References DiskStats::available, DiskInfo::count, DiskStats::device, DiskInfo::disks, DiskStats::free, get_disk_io_stats(), DiskStats::io_in_progress, is_real_disk(), MAX_DISK_NAME, MAX_DISKS, MAX_MOUNT_PATH, DiskStats::mount_point, prev_reads, prev_writes, DiskStats::reads, DiskStats::total, DiskStats::usage, and DiskStats::writes.
Referenced by update_stats().