System Monitor: src/stats.c File Reference
stats.c File Reference
Implementation of system statistics gathering functions.
#include "system_monitor.h"
#include <stdio.h>
Functions
int update_stats (SystemStats *stats)
Updates all system statistics.
Detailed Description
Implementation of system statistics gathering functions.
This file contains the implementation of functions that gather and update various system statistics including CPU, memory, disk, and GPU information. It serves as the central point for collecting all system metrics.
Definition in file stats.c.
Function Documentation
update_stats()
int update_stats (SystemStats * stats)
Updates all system statistics.
Update system statistics.
Parameters
stats Pointer to SystemStats structure to be updated
Returns
0 on successful update of all statistics, -1 if any update fails
This function coordinates the update of all system statistics by calling individual update functions for each subsystem (CPU, memory, disk, GPU). If any of these updates fail, the function returns immediately with -1.
Note
All statistics are updated atomically - either all succeed or none are updated
Warning
The stats parameter must not be NULL
Definition at line 26 of file stats.c.
References SystemStats::cpu, SystemStats::disks, SystemStats::gpus, SystemStats::memory, update_cpu_stats(), update_disk_stats(), update_gpu_stats(), and update_memory_stats().
Referenced by main().