System Monitor: src/display.c File Reference
display.c File Reference
Implementation of display-related functions.
#include "system_monitor.h"
#include <stdio.h>
Macros
#define CPU_WIN_HEIGHT 4
#define DISK_WIN_HEIGHT 12
#define GPU_WIN_HEIGHT 12
#define MEM_WIN_HEIGHT 5
#define WIN_WIDTH 60
Functions
void cleanup_display (void)
Clean up and close the ncurses interface.
void display_stats (const SystemStats *stats)
Display system statistics on the screen.
static void format_bytes (unsigned long bytes, char *buf, size_t size)
Convert bytes to human readable format.
static int get_temp_color (int temp)
static int get_usage_color (double usage)
int init_display (void)
Initialize the ncurses interface.
Variables
static WINDOW * cpu_win = NULL
static WINDOW * disk_win = NULL
static WINDOW * gpu_win = NULL
static WINDOW * mem_win = NULL
Detailed Description
Implementation of display-related functions.
Definition in file display.c.
Macro Definition Documentation
CPU_WIN_HEIGHT
#define CPU_WIN_HEIGHT 4
Definition at line 10 of file display.c.
DISK_WIN_HEIGHT
#define DISK_WIN_HEIGHT 12
Definition at line 12 of file display.c.
GPU_WIN_HEIGHT
#define GPU_WIN_HEIGHT 12
Definition at line 13 of file display.c.
MEM_WIN_HEIGHT
#define MEM_WIN_HEIGHT 5
Definition at line 11 of file display.c.
WIN_WIDTH
#define WIN_WIDTH 60
Definition at line 14 of file display.c.
Function Documentation
cleanup_display()
void cleanup_display (void)
Clean up and close the ncurses interface.
Properly closes the ncurses window and restores terminal settings. Should be called before program exit to ensure proper cleanup.
Definition at line 126 of file display.c.
References cpu_win, disk_win, gpu_win, and mem_win.
Referenced by main().
display_stats()
void display_stats (const SystemStats * stats)
Display system statistics on the screen.
Parameters
stats Pointer to SystemStats structure containing current statistics
Renders the current system statistics in a formatted layout using ncurses. Updates the entire display with fresh data from the stats structure.
Note
init_display() must be called before using this function
Warning
The stats parameter must not be NULL and contain valid data
Definition at line 148 of file display.c.
References DiskStats::available, MemoryStats::available, MemoryStats::buffers, MemoryStats::cached, CPUStats::cores, DiskInfo::count, GPUInfo::count, SystemStats::cpu, cpu_win, DiskStats::device, disk_win, DISK_WIN_HEIGHT, DiskInfo::disks, SystemStats::disks, GPUStats::fan_speed, format_bytes(), get_temp_color(), get_usage_color(), gpu_win, GPU_WIN_HEIGHT, GPUInfo::gpus, SystemStats::gpus, DiskStats::io_in_progress, mem_win, SystemStats::memory, GPUStats::memory_total, GPUStats::memory_used, CPUStats::model_name, DiskStats::mount_point, GPUStats::name, GPUStats::power_usage, DiskStats::reads, GPUStats::supported, MemoryStats::swap_free, MemoryStats::swap_total, MemoryStats::swap_usage, GPUStats::temperature, DiskStats::total, MemoryStats::total, CPUStats::usage, DiskStats::usage, MemoryStats::usage, MemoryStats::used, GPUStats::utilization, WIN_WIDTH, and DiskStats::writes.
Referenced by main().
format_bytes()
static void format_bytes (unsigned long bytes, char * buf, size_t size) static
Convert bytes to human readable format.
Parameters
bytes Number of bytes
buf Buffer to store the result
size Size of the buffer
Definition at line 28 of file display.c.
Referenced by display_stats().
get_temp_color()
static int get_temp_color (int temp) static
Definition at line 141 of file display.c.
Referenced by display_stats().
get_usage_color()
static int get_usage_color (double usage) static
Definition at line 134 of file display.c.
Referenced by display_stats().
init_display()
int init_display (void)
Initialize the ncurses interface.
Returns
0 on successful initialization, -1 on failure
Sets up the ncurses window, configures colors if available, and prepares the display layout. Must be called before any display operations.
Note
The terminal must support ncurses operations
Definition at line 41 of file display.c.
References cpu_win, CPU_WIN_HEIGHT, disk_win, DISK_WIN_HEIGHT, gpu_win, GPU_WIN_HEIGHT, mem_win, MEM_WIN_HEIGHT, and WIN_WIDTH.
Referenced by main().
Variable Documentation
cpu_win
WINDOW* cpu_win = NULL static
Definition at line 17 of file display.c.
Referenced by cleanup_display(), display_stats(), and init_display().
disk_win
WINDOW* disk_win = NULL static
Definition at line 19 of file display.c.
Referenced by cleanup_display(), display_stats(), and init_display().
gpu_win
WINDOW* gpu_win = NULL static
Definition at line 20 of file display.c.
Referenced by cleanup_display(), display_stats(), and init_display().
mem_win
WINDOW* mem_win = NULL static
Definition at line 18 of file display.c.
Referenced by cleanup_display(), display_stats(), and init_display().