System Monitor: include/network.h File Reference
network.h File Reference
Network interface monitoring functionality.
#include <stddef.h>
Data Structures
struct NetworkInterfaceStats
Structure to hold statistics for a single network interface.
struct NetworkStats
Structure to hold all network interface statistics.
Macros
#define INTERFACE_NAME_MAX 32
#define MAX_INTERFACES 16
Functions
void cleanup_network_monitoring (void)
Clean up network monitoring resources.
int init_network_monitoring (void)
Initialize network monitoring.
int update_network_stats (NetworkStats *stats)
Update network statistics.
Detailed Description
Network interface monitoring functionality.
Definition in file network.h.
Macro Definition Documentation
INTERFACE_NAME_MAX
#define INTERFACE_NAME_MAX 32
Definition at line 12 of file network.h.
MAX_INTERFACES
#define MAX_INTERFACES 16
Definition at line 11 of file network.h.
Function Documentation
cleanup_network_monitoring()
void cleanup_network_monitoring (void)
Clean up network monitoring resources.
Definition at line 128 of file network.c.
Referenced by main().
init_network_monitoring()
int init_network_monitoring (void)
Initialize network monitoring.
Returns
0 on success, -1 on failure
Definition at line 28 of file network.c.
References previous_stats, and PROC_NET_DEV.
Referenced by main().
update_network_stats()
int update_network_stats (NetworkStats * stats)
Update network statistics.
Parameters
stats Pointer to NetworkStats structure to update
Returns
0 on success, -1 on failure
Definition at line 98 of file network.c.
References calculate_speeds(), NetworkStats::interface_count, NetworkStats::interfaces, LINE_BUF_SIZE, MAX_INTERFACES, parse_interface_line(), previous_stats, and PROC_NET_DEV.
Referenced by update_stats().