System Monitor: src/disk.c File Reference
disk.c File Reference
Implementation of disk monitoring functionality.
#include "disk.h"
#include <stdio.h>
#include <string.h>
#include <sys/statvfs.h>
#include <mntent.h>
#include <unistd.h>
#include <ctype.h>
Functions
void cleanup_disk_monitor (void)
Clean up disk monitoring resources.
static int get_disk_io_stats (const char *device, unsigned long *reads, unsigned long *writes, unsigned long *io_in_progress)
Get disk I/O statistics from /proc/diskstats.
int init_disk_monitor (void)
Initialize disk monitoring.
static int is_real_disk (const char *device)
Check if a device name corresponds to a real disk.
int update_disk_stats (DiskInfo *info)
Update disk statistics.
Variables
static unsigned long prev_reads [8] = {0}
static unsigned long prev_writes [8] = {0}
Detailed Description
Implementation of disk monitoring functionality.
Definition in file disk.c.
Function Documentation
cleanup_disk_monitor()
void cleanup_disk_monitor (void)
Clean up disk monitoring resources.
Definition at line 155 of file disk.c.
Referenced by main().
get_disk_io_stats()
static int get_disk_io_stats (const char * device, unsigned long * reads, unsigned long * writes, unsigned long * io_in_progress) static
Get disk I/O statistics from /proc/diskstats.
Parameters
device Device name
reads Pointer to store number of reads
writes Pointer to store number of writes
io_in_progress Pointer to store number of I/O operations in progress
Returns
0 on success, -1 on failure
Definition at line 40 of file disk.c.
Referenced by update_disk_stats().
init_disk_monitor()
int init_disk_monitor (void)
Initialize disk monitoring.
Returns
0 on success, -1 on failure
Definition at line 92 of file disk.c.
References prev_reads, and prev_writes.
Referenced by main().
is_real_disk()
static int is_real_disk (const char * device) static
Check if a device name corresponds to a real disk.
Parameters
device Device name to check
Returns
1 if it's a real disk, 0 otherwise
Definition at line 23 of file disk.c.
Referenced by update_disk_stats().
update_disk_stats()
int update_disk_stats (DiskInfo * stats)
Update disk statistics.
Parameters
stats Pointer to DiskInfo structure to update
Returns
0 on success, -1 on failure
Definition at line 98 of file disk.c.
References DiskStats::available, DiskInfo::count, DiskStats::device, DiskInfo::disks, DiskStats::free, get_disk_io_stats(), DiskStats::io_in_progress, is_real_disk(), MAX_DISK_NAME, MAX_DISKS, MAX_MOUNT_PATH, DiskStats::mount_point, prev_reads, prev_writes, DiskStats::reads, DiskStats::total, DiskStats::usage, and DiskStats::writes.
Referenced by update_stats().
Variable Documentation
prev_reads
unsigned long prev_reads[8] = {0} static
Definition at line 15 of file disk.c.
Referenced by init_disk_monitor(), and update_disk_stats().
prev_writes
unsigned long prev_writes[8] = {0} static
Definition at line 16 of file disk.c.
Referenced by init_disk_monitor(), and update_disk_stats().