System Monitor: include/cpu.h File Reference
cpu.h File Reference
CPU monitoring functionality.
Data Structures
struct CPUStats
Structure to hold CPU statistics.
Functions
void cleanup_cpu_monitor (void)
Clean up CPU monitoring resources.
int init_cpu_monitor (void)
Initialize CPU monitoring.
int update_cpu_stats (CPUStats *stats)
Update CPU statistics.
Detailed Description
CPU monitoring functionality.
Definition in file cpu.h.
Function Documentation
cleanup_cpu_monitor()
void cleanup_cpu_monitor (void)
Clean up CPU monitoring resources.
Definition at line 110 of file cpu.c.
Referenced by main().
init_cpu_monitor()
int init_cpu_monitor (void)
Initialize CPU monitoring.
Returns
0 on success, -1 on failure
Definition at line 72 of file cpu.c.
References prev_idle, and prev_total.
Referenced by main().
update_cpu_stats()
int update_cpu_stats (CPUStats * stats)
Update CPU statistics.
Parameters
stats Pointer to CPUStats structure to update
Returns
0 on success, -1 on failure
Definition at line 78 of file cpu.c.
References CPUStats::cores, get_cpu_model(), CPUStats::model_name, prev_idle, prev_total, read_cpu_stats(), and CPUStats::usage.
Referenced by update_stats().