System Monitor: NVMLFunctions Struct Reference
NVMLFunctions Struct Reference
Data Fields
void * handle
int(* nvmlDeviceGetCount)(unsigned int *)
int(* nvmlDeviceGetFanSpeed)(void *, unsigned int *)
int(* nvmlDeviceGetHandleByIndex)(unsigned int, void **)
int(* nvmlDeviceGetMemoryInfo)(void *, void *)
int(* nvmlDeviceGetName)(void *, char *, unsigned int)
int(* nvmlDeviceGetPowerUsage)(void *, unsigned int *)
int(* nvmlDeviceGetTemperature)(void *, int, unsigned int *)
int(* nvmlDeviceGetUtilizationRates)(void *, void *)
int(* nvmlInit)(void)
int(* nvmlShutdown)(void)
Detailed Description
Definition at line 13 of file gpu.c.
Field Documentation
handle
void* NVMLFunctions::handle
Definition at line 14 of file gpu.c.
Referenced by cleanup_gpu_monitor(), load_nvml(), and update_gpu_stats().
nvmlDeviceGetCount
int(* NVMLFunctions::nvmlDeviceGetCount) (unsigned int *)
Definition at line 17 of file gpu.c.
Referenced by load_nvml(), and update_gpu_stats().
nvmlDeviceGetFanSpeed
int(* NVMLFunctions::nvmlDeviceGetFanSpeed) (void *, unsigned int *)
Definition at line 24 of file gpu.c.
Referenced by load_nvml(), and update_gpu_stats().
nvmlDeviceGetHandleByIndex
int(* NVMLFunctions::nvmlDeviceGetHandleByIndex) (unsigned int, void **)
Definition at line 18 of file gpu.c.
Referenced by load_nvml(), and update_gpu_stats().
nvmlDeviceGetMemoryInfo
int(* NVMLFunctions::nvmlDeviceGetMemoryInfo) (void *, void *)
Definition at line 22 of file gpu.c.
Referenced by load_nvml(), and update_gpu_stats().
nvmlDeviceGetName
int(* NVMLFunctions::nvmlDeviceGetName) (void *, char *, unsigned int)
Definition at line 19 of file gpu.c.
Referenced by load_nvml(), and update_gpu_stats().
nvmlDeviceGetPowerUsage
int(* NVMLFunctions::nvmlDeviceGetPowerUsage) (void *, unsigned int *)
Definition at line 23 of file gpu.c.
Referenced by load_nvml(), and update_gpu_stats().
nvmlDeviceGetTemperature
int(* NVMLFunctions::nvmlDeviceGetTemperature) (void *, int, unsigned int *)
Definition at line 20 of file gpu.c.
Referenced by load_nvml(), and update_gpu_stats().
nvmlDeviceGetUtilizationRates
int(* NVMLFunctions::nvmlDeviceGetUtilizationRates) (void *, void *)
Definition at line 21 of file gpu.c.
Referenced by load_nvml(), and update_gpu_stats().
nvmlInit
int(* NVMLFunctions::nvmlInit) (void)
Definition at line 15 of file gpu.c.
Referenced by init_gpu_monitor(), and load_nvml().
nvmlShutdown
int(* NVMLFunctions::nvmlShutdown) (void)
Definition at line 16 of file gpu.c.
Referenced by cleanup_gpu_monitor(), and load_nvml().
The documentation for this struct was generated from the following file:
src/gpu.c