System Monitor: include/system_monitor.h File Reference
system_monitor.h File Reference
Main header file for the system monitor application.
#include <ncurses.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "cpu.h"
#include "memory.h"
#include "disk.h"
#include "gpu.h"
Data Structures
struct SystemStats
Structure to hold system statistics.
Functions
void cleanup_display (void)
Clean up and close the ncurses interface.
void display_stats (const SystemStats *stats)
Display system statistics on the screen.
int init_display (void)
Initialize the ncurses interface.
int update_stats (SystemStats *stats)
Update system statistics.
Detailed Description
Main header file for the system monitor application.
This header defines the main structures and functions for the system monitoring application. It includes functionality for monitoring CPU, memory, disk, and GPU statistics, as well as the ncurses-based user interface.
Definition in file system_monitor.h.
Function Documentation
cleanup_display()
void cleanup_display (void)
Clean up and close the ncurses interface.
Properly closes the ncurses window and restores terminal settings. Should be called before program exit to ensure proper cleanup.
Definition at line 126 of file display.c.
References cpu_win, disk_win, gpu_win, and mem_win.
Referenced by main().
display_stats()
void display_stats (const SystemStats * stats)
Display system statistics on the screen.
Parameters
stats Pointer to SystemStats structure containing current statistics
Renders the current system statistics in a formatted layout using ncurses. Updates the entire display with fresh data from the stats structure.
Note
init_display() must be called before using this function
Warning
The stats parameter must not be NULL and contain valid data
Definition at line 148 of file display.c.
References DiskStats::available, MemoryStats::available, MemoryStats::buffers, MemoryStats::cached, CPUStats::cores, DiskInfo::count, GPUInfo::count, SystemStats::cpu, cpu_win, DiskStats::device, disk_win, DISK_WIN_HEIGHT, DiskInfo::disks, SystemStats::disks, GPUStats::fan_speed, format_bytes(), get_temp_color(), get_usage_color(), gpu_win, GPU_WIN_HEIGHT, GPUInfo::gpus, SystemStats::gpus, DiskStats::io_in_progress, mem_win, SystemStats::memory, GPUStats::memory_total, GPUStats::memory_used, CPUStats::model_name, DiskStats::mount_point, GPUStats::name, GPUStats::power_usage, DiskStats::reads, GPUStats::supported, MemoryStats::swap_free, MemoryStats::swap_total, MemoryStats::swap_usage, GPUStats::temperature, DiskStats::total, MemoryStats::total, CPUStats::usage, DiskStats::usage, MemoryStats::usage, MemoryStats::used, GPUStats::utilization, WIN_WIDTH, and DiskStats::writes.
Referenced by main().
init_display()
int init_display (void)
Initialize the ncurses interface.
Returns
0 on successful initialization, -1 on failure
Sets up the ncurses window, configures colors if available, and prepares the display layout. Must be called before any display operations.
Note
The terminal must support ncurses operations
Definition at line 41 of file display.c.
References cpu_win, CPU_WIN_HEIGHT, disk_win, DISK_WIN_HEIGHT, gpu_win, GPU_WIN_HEIGHT, mem_win, MEM_WIN_HEIGHT, and WIN_WIDTH.
Referenced by main().
update_stats()
int update_stats (SystemStats * stats)
Update system statistics.
Parameters
stats Pointer to SystemStats structure to update
Returns
0 on success, -1 on failure
Gathers fresh statistics from all monitored subsystems and updates the provided SystemStats structure. This is the main function for collecting system metrics.
Warning
The stats parameter must not be NULL
Update system statistics.
Parameters
stats Pointer to SystemStats structure to be updated
Returns
0 on successful update of all statistics, -1 if any update fails
This function coordinates the update of all system statistics by calling individual update functions for each subsystem (CPU, memory, disk, GPU). If any of these updates fail, the function returns immediately with -1.
Note
All statistics are updated atomically - either all succeed or none are updated
Warning
The stats parameter must not be NULL
Definition at line 26 of file stats.c.
References SystemStats::cpu, SystemStats::disks, SystemStats::gpus, SystemStats::memory, update_cpu_stats(), update_disk_stats(), update_gpu_stats(), and update_memory_stats().
Referenced by main().