System Monitor: src/memory.c File Reference
memory.c File Reference
Implementation of memory monitoring functionality.
#include "memory.h"
#include <stdio.h>
#include <string.h>
#include <sys/sysinfo.h>
Macros
#define GB_TO_BYTES (1024UL * 1024UL * 1024UL)
#define KB_TO_BYTES (1024UL)
#define MB_TO_BYTES (1024UL * 1024UL)
Functions
void cleanup_memory_monitor (void)
int init_memory_monitor (void)
static int read_proc_meminfo (MemoryStats *stats)
Read memory information from /proc/meminfo.
int update_memory_stats (MemoryStats *stats)
Update memory statistics.
Detailed Description
Implementation of memory monitoring functionality.
Definition in file memory.c.
Macro Definition Documentation
GB_TO_BYTES
#define GB_TO_BYTES (1024UL * 1024UL * 1024UL)
Definition at line 14 of file memory.c.
KB_TO_BYTES
#define KB_TO_BYTES (1024UL)
Definition at line 12 of file memory.c.
MB_TO_BYTES
#define MB_TO_BYTES (1024UL * 1024UL)
Definition at line 13 of file memory.c.
Function Documentation
cleanup_memory_monitor()
void cleanup_memory_monitor (void)
Definition at line 89 of file memory.c.
Referenced by main().
init_memory_monitor()
int init_memory_monitor (void)
Definition at line 80 of file memory.c.
Referenced by main().
read_proc_meminfo()
static int read_proc_meminfo (MemoryStats * stats) static
Read memory information from /proc/meminfo.
Parameters
stats Pointer to MemoryStats structure to update
Returns
0 on success, -1 on failure
Definition at line 21 of file memory.c.
References MemoryStats::available, MemoryStats::buffers, MemoryStats::cached, MemoryStats::free, KB_TO_BYTES, MemoryStats::swap_free, MemoryStats::swap_total, MemoryStats::swap_usage, MemoryStats::total, MemoryStats::usage, and MemoryStats::used.
Referenced by update_memory_stats().
update_memory_stats()
int update_memory_stats (MemoryStats * stats)
Update memory statistics.
Parameters
stats Pointer to MemoryStats structure to update
Returns
0 on success, -1 on failure
Reads current memory information from the system and updates all fields in the provided MemoryStats structure. This includes calculating derived values like usage percentages.
Note
Requires prior call to init_memory_monitoring()
Warning
The stats parameter must not be NULL
Definition at line 84 of file memory.c.
References read_proc_meminfo().
Referenced by update_stats().