System Monitor: src/gpu.c File Reference
gpu.c File Reference
Implementation of GPU monitoring functionality.
#include "gpu.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <dlfcn.h>
Data Structures
struct NVMLFunctions
Functions
void cleanup_gpu_monitor (void)
Clean up GPU monitoring resources.
int init_gpu_monitor (void)
Initialize GPU monitoring.
static int load_nvml (void)
Load NVIDIA NVML library and functions.
static void read_sysfs_gpu_info (GPUInfo *info)
Try to read GPU information from sysfs (for non-NVIDIA GPUs)
int update_gpu_stats (GPUInfo *info)
Update GPU statistics.
Variables
static NVMLFunctions nvml = {0}
Detailed Description
Implementation of GPU monitoring functionality.
Definition in file gpu.c.
Function Documentation
cleanup_gpu_monitor()
void cleanup_gpu_monitor (void)
Clean up GPU monitoring resources.
Definition at line 184 of file gpu.c.
References NVMLFunctions::handle, nvml, and NVMLFunctions::nvmlShutdown.
Referenced by main().
init_gpu_monitor()
int init_gpu_monitor (void)
Initialize GPU monitoring.
Returns
0 on success, -1 on failure
Definition at line 103 of file gpu.c.
References load_nvml(), nvml, and NVMLFunctions::nvmlInit.
Referenced by main().
load_nvml()
static int load_nvml (void) static
Load NVIDIA NVML library and functions.
Returns
0 on success, -1 on failure
Definition at line 33 of file gpu.c.
References NVMLFunctions::handle, nvml, NVMLFunctions::nvmlDeviceGetCount, NVMLFunctions::nvmlDeviceGetFanSpeed, NVMLFunctions::nvmlDeviceGetHandleByIndex, NVMLFunctions::nvmlDeviceGetMemoryInfo, NVMLFunctions::nvmlDeviceGetName, NVMLFunctions::nvmlDeviceGetPowerUsage, NVMLFunctions::nvmlDeviceGetTemperature, NVMLFunctions::nvmlDeviceGetUtilizationRates, NVMLFunctions::nvmlInit, and NVMLFunctions::nvmlShutdown.
Referenced by init_gpu_monitor().
read_sysfs_gpu_info()
static void read_sysfs_gpu_info (GPUInfo * info) static
Try to read GPU information from sysfs (for non-NVIDIA GPUs)
Parameters
info Pointer to GPUInfo structure
Definition at line 65 of file gpu.c.
References GPUInfo::count, GPUInfo::gpus, MAX_GPU_NAME, MAX_GPUS, GPUStats::name, and GPUStats::supported.
Referenced by update_gpu_stats().
update_gpu_stats()
int update_gpu_stats (GPUInfo * info)
Update GPU statistics.
Parameters
info Pointer to GPUInfo structure to update
Returns
0 on success, -1 on failure
Definition at line 113 of file gpu.c.
References GPUInfo::count, GPUStats::fan_speed, GPUInfo::gpus, NVMLFunctions::handle, MAX_GPU_NAME, MAX_GPUS, GPUStats::memory_free, GPUStats::memory_total, GPUStats::memory_used, GPUStats::name, GPUInfo::nvidia_available, nvml, NVMLFunctions::nvmlDeviceGetCount, NVMLFunctions::nvmlDeviceGetFanSpeed, NVMLFunctions::nvmlDeviceGetHandleByIndex, NVMLFunctions::nvmlDeviceGetMemoryInfo, NVMLFunctions::nvmlDeviceGetName, NVMLFunctions::nvmlDeviceGetPowerUsage, NVMLFunctions::nvmlDeviceGetTemperature, NVMLFunctions::nvmlDeviceGetUtilizationRates, GPUStats::power_usage, read_sysfs_gpu_info(), GPUStats::supported, GPUStats::temperature, and GPUStats::utilization.
Referenced by update_stats().
Variable Documentation
nvml
NVMLFunctions nvml = {0} static
Definition at line 27 of file gpu.c.
Referenced by cleanup_gpu_monitor(), init_gpu_monitor(), load_nvml(), and update_gpu_stats().