System Monitor: include/gpu.h File Reference
gpu.h File Reference
GPU monitoring functionality.
Data Structures
struct GPUInfo
Structure to hold all GPU information.
struct GPUStats
Structure to hold GPU statistics.
Macros
#define MAX_GPU_NAME 128
#define MAX_GPUS 4
Functions
void cleanup_gpu_monitor (void)
Clean up GPU monitoring resources.
int init_gpu_monitor (void)
Initialize GPU monitoring.
int update_gpu_stats (GPUInfo *info)
Update GPU statistics.
Detailed Description
GPU monitoring functionality.
Definition in file gpu.h.
Macro Definition Documentation
MAX_GPU_NAME
#define MAX_GPU_NAME 128
Definition at line 10 of file gpu.h.
MAX_GPUS
#define MAX_GPUS 4
Definition at line 9 of file gpu.h.
Function Documentation
cleanup_gpu_monitor()
void cleanup_gpu_monitor (void)
Clean up GPU monitoring resources.
Definition at line 184 of file gpu.c.
References NVMLFunctions::handle, nvml, and NVMLFunctions::nvmlShutdown.
Referenced by main().
init_gpu_monitor()
int init_gpu_monitor (void)
Initialize GPU monitoring.
Returns
0 on success, -1 on failure
Definition at line 103 of file gpu.c.
References load_nvml(), nvml, and NVMLFunctions::nvmlInit.
Referenced by main().
update_gpu_stats()
int update_gpu_stats (GPUInfo * info)
Update GPU statistics.
Parameters
info Pointer to GPUInfo structure to update
Returns
0 on success, -1 on failure
Definition at line 113 of file gpu.c.
References GPUInfo::count, GPUStats::fan_speed, GPUInfo::gpus, NVMLFunctions::handle, MAX_GPU_NAME, MAX_GPUS, GPUStats::memory_free, GPUStats::memory_total, GPUStats::memory_used, GPUStats::name, GPUInfo::nvidia_available, nvml, NVMLFunctions::nvmlDeviceGetCount, NVMLFunctions::nvmlDeviceGetFanSpeed, NVMLFunctions::nvmlDeviceGetHandleByIndex, NVMLFunctions::nvmlDeviceGetMemoryInfo, NVMLFunctions::nvmlDeviceGetName, NVMLFunctions::nvmlDeviceGetPowerUsage, NVMLFunctions::nvmlDeviceGetTemperature, NVMLFunctions::nvmlDeviceGetUtilizationRates, GPUStats::power_usage, read_sysfs_gpu_info(), GPUStats::supported, GPUStats::temperature, and GPUStats::utilization.
Referenced by update_stats().