System Monitor: Core System
Core System
Core system functionality and data structures.
Data Structures
struct SystemStats
Structure to hold system statistics.
Functions
void cleanup_display (void)
Clean up and close the ncurses interface.
void display_stats (const SystemStats *stats)
Display system statistics on the screen.
int init_display (void)
Initialize the ncurses interface.
int update_stats (SystemStats *stats)
Update system statistics.
Detailed Description
Core system functionality and data structures.
The core system module provides the main functionality for coordinating different monitoring subsystems and managing the user interface.
Function Documentation
cleanup_display()
void cleanup_display (void)
Clean up and close the ncurses interface.
Properly closes the ncurses window and restores terminal settings. Should be called before program exit to ensure proper cleanup.
See also
init_display
Definition at line 192 of file display.c.
References cpu_win, disk_win, gpu_win, header_win, mem_win, and net_win.
Referenced by init_display(), and main().
display_stats()
void display_stats (const SystemStats * stats)
Display system statistics on the screen.
Parameters
stats Pointer to SystemStats structure containing current statistics
Renders the current system statistics in a formatted layout using ncurses. Updates the entire display with fresh data from the stats structure.
Note
init_display() must be called before using this function
Warning
The stats parameter must not be NULL and contain valid data
See also
init_display
SystemStats
Display system statistics on the screen.
Parameters
stats Pointer to SystemStats structure containing current statistics
Definition at line 206 of file display.c.
References DiskStats::available, MemoryStats::cached, CPUStats::cores, DiskInfo::count, GPUInfo::count, SystemStats::cpu, cpu_win, disk_win, DiskInfo::disks, SystemStats::disks, draw_fancy_box(), format_bytes(), format_speed(), MemoryStats::free, gpu_win, GPUInfo::gpus, SystemStats::gpus, header_win, NetworkInterfaceStats::interface, NetworkStats::interface_count, NetworkStats::interfaces, mem_win, SystemStats::memory, GPUStats::memory_total, GPUStats::memory_used, CPUStats::model_name, DiskStats::mount_point, GPUStats::name, net_win, SystemStats::network, NetworkInterfaceStats::receive_speed, NetworkInterfaceStats::send_speed, MemoryStats::swap_usage, GPUStats::temperature, DiskStats::total, MemoryStats::total, CPUStats::usage, DiskStats::usage, MemoryStats::usage, MemoryStats::used, GPUStats::utilization, and WIN_WIDTH.
Referenced by main().
init_display()
int init_display (void)
Initialize the ncurses interface.
Returns
0 on successful initialization, -1 on failure
Sets up the ncurses window, configures colors if available, and prepares the display layout. Must be called before any display operations.
Note
The terminal must support ncurses operations
See also
cleanup_display
Definition at line 102 of file display.c.
References cleanup_display(), COLOR_BORDER, COLOR_CRITICAL, COLOR_GOOD, COLOR_HEADER, COLOR_NORMAL, COLOR_WARNING, cpu_win, CPU_WIN_HEIGHT, create_centered_win(), disk_win, DISK_WIN_HEIGHT, draw_fancy_box(), gpu_win, GPU_WIN_HEIGHT, HEADER_HEIGHT, header_win, mem_win, MEM_WIN_HEIGHT, net_win, NET_WIN_HEIGHT, PADDING, and WIN_WIDTH.
Referenced by main().
update_stats()
int update_stats (SystemStats * stats)
Update system statistics.
Parameters
stats Pointer to SystemStats structure to update
Returns
0 on success, -1 on failure
Gathers fresh statistics from all monitored subsystems and updates the provided SystemStats structure. This is the main function for collecting system metrics.
Warning
The stats parameter must not be NULL
See also
SystemStats
Update system statistics.
Parameters
stats Pointer to SystemStats structure to be updated
Returns
0 on successful update of all statistics, -1 if any update fails
This function coordinates the update of all system statistics by calling individual update functions for each subsystem (CPU, memory, disk, GPU, network). If any of these updates fail, the function returns immediately with -1.
Note
All statistics are updated atomically - either all succeed or none are updated
Warning
The stats parameter must not be NULL
Definition at line 26 of file stats.c.
References SystemStats::cpu, SystemStats::disks, SystemStats::gpus, SystemStats::memory, SystemStats::network, update_cpu_stats(), update_disk_stats(), update_gpu_stats(), update_memory_stats(), and update_network_stats().
Referenced by main().