System Monitor: src/cpu.c File Reference
cpu.c File Reference
Implementation of CPU monitoring functionality.
#include "cpu.h"
#include <stdio.h>
#include <string.h>
#include <unistd.h>
Functions
void cleanup_cpu_monitor (void)
Clean up CPU monitoring resources.
static int get_cpu_model (char *model_name, size_t size)
Get CPU model name from /proc/cpuinfo.
int init_cpu_monitor (void)
Initialize CPU monitoring.
static int read_cpu_stats (unsigned long long *idle, unsigned long long *total)
Read CPU statistics from /proc/stat.
int update_cpu_stats (CPUStats *stats)
Update CPU statistics.
Variables
static unsigned long long prev_idle = 0
static unsigned long long prev_total = 0
Detailed Description
Implementation of CPU monitoring functionality.
Definition in file cpu.c.
Function Documentation
cleanup_cpu_monitor()
void cleanup_cpu_monitor (void)
Clean up CPU monitoring resources.
Definition at line 110 of file cpu.c.
Referenced by main().
get_cpu_model()
static int get_cpu_model (char * model_name, size_t size) static
Get CPU model name from /proc/cpuinfo.
Parameters
model_name Buffer to store the model name
size Size of the buffer
Returns
0 on success, -1 on failure
Definition at line 45 of file cpu.c.
Referenced by update_cpu_stats().
init_cpu_monitor()
int init_cpu_monitor (void)
Initialize CPU monitoring.
Returns
0 on success, -1 on failure
Definition at line 72 of file cpu.c.
References prev_idle, and prev_total.
Referenced by main().
read_cpu_stats()
static int read_cpu_stats (unsigned long long * idle, unsigned long long * total) static
Read CPU statistics from /proc/stat.
Parameters
idle Pointer to store idle time
total Pointer to store total time
Returns
0 on success, -1 on failure
Definition at line 21 of file cpu.c.
Referenced by update_cpu_stats().
update_cpu_stats()
int update_cpu_stats (CPUStats * stats)
Update CPU statistics.
Parameters
stats Pointer to CPUStats structure to update
Returns
0 on success, -1 on failure
Definition at line 78 of file cpu.c.
References CPUStats::cores, get_cpu_model(), CPUStats::model_name, prev_idle, prev_total, read_cpu_stats(), and CPUStats::usage.
Referenced by update_stats().
Variable Documentation
prev_idle
unsigned long long prev_idle = 0 static
Definition at line 12 of file cpu.c.
Referenced by init_cpu_monitor(), and update_cpu_stats().
prev_total
unsigned long long prev_total = 0 static
Definition at line 13 of file cpu.c.
Referenced by init_cpu_monitor(), and update_cpu_stats().