System Monitor: src/network.c File Reference
network.c File Reference
Implementation of network monitoring functionality.
#include "network.h"
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct PreviousStats
Macros
#define LINE_BUF_SIZE 512
#define PROC_NET_DEV "/proc/net/dev"
Functions
static void calculate_speeds (NetworkInterfaceStats *current, PreviousStats *prev)
Calculate interface speeds.
void cleanup_network_monitoring (void)
Clean up network monitoring resources.
int init_network_monitoring (void)
Initialize network monitoring.
static int parse_interface_line (char *line, NetworkInterfaceStats *stats)
Parse a single line from /proc/net/dev.
int update_network_stats (NetworkStats *stats)
Update network statistics.
Variables
static PreviousStats previous_stats [16]
Detailed Description
Implementation of network monitoring functionality.
Definition in file network.c.
Macro Definition Documentation
LINE_BUF_SIZE
#define LINE_BUF_SIZE 512
Definition at line 13 of file network.c.
PROC_NET_DEV
#define PROC_NET_DEV "/proc/net/dev"
Definition at line 12 of file network.c.
Function Documentation
calculate_speeds()
static void calculate_speeds (NetworkInterfaceStats * current, PreviousStats * prev) static
Calculate interface speeds.
Parameters
current Current interface statistics
prev Previous interface statistics
Definition at line 75 of file network.c.
References NetworkInterfaceStats::bytes_received, PreviousStats::bytes_received, NetworkInterfaceStats::bytes_sent, PreviousStats::bytes_sent, NetworkInterfaceStats::receive_speed, NetworkInterfaceStats::send_speed, and PreviousStats::timestamp.
Referenced by update_network_stats().
cleanup_network_monitoring()
void cleanup_network_monitoring (void)
Clean up network monitoring resources.
Definition at line 128 of file network.c.
Referenced by main().
init_network_monitoring()
int init_network_monitoring (void)
Initialize network monitoring.
Returns
0 on success, -1 on failure
Definition at line 28 of file network.c.
References previous_stats, and PROC_NET_DEV.
Referenced by main().
parse_interface_line()
static int parse_interface_line (char * line, NetworkInterfaceStats * stats) static
Parse a single line from /proc/net/dev.
Parameters
line The line to parse
stats Pointer to NetworkInterfaceStats to update
Returns
0 on success, -1 on failure
Definition at line 45 of file network.c.
References NetworkInterfaceStats::bytes_received, NetworkInterfaceStats::bytes_sent, NetworkInterfaceStats::drops_in, NetworkInterfaceStats::drops_out, NetworkInterfaceStats::errors_in, NetworkInterfaceStats::errors_out, NetworkInterfaceStats::interface, INTERFACE_NAME_MAX, NetworkInterfaceStats::packets_received, and NetworkInterfaceStats::packets_sent.
Referenced by update_network_stats().
update_network_stats()
int update_network_stats (NetworkStats * stats)
Update network statistics.
Parameters
stats Pointer to NetworkStats structure to update
Returns
0 on success, -1 on failure
Definition at line 98 of file network.c.
References calculate_speeds(), NetworkStats::interface_count, NetworkStats::interfaces, LINE_BUF_SIZE, MAX_INTERFACES, parse_interface_line(), previous_stats, and PROC_NET_DEV.
Referenced by update_stats().
Variable Documentation
previous_stats
PreviousStats previous_stats[16] static
Definition at line 22 of file network.c.
Referenced by init_network_monitoring(), and update_network_stats().