System Monitor: src/main.c File Reference
main.c File Reference
Main entry point for the system monitor application.
#include "system_monitor.h"
#include <signal.h>
Functions
int main (void)
void sig_handler (int sig)
Signal handler for clean program termination.
Variables
static volatile int keep_running = 1
Detailed Description
Main entry point for the system monitor application.
Definition in file main.c.
Function Documentation
main()
int main (void)
Definition at line 20 of file main.c.
References cleanup_cpu_monitor(), cleanup_disk_monitor(), cleanup_display(), cleanup_gpu_monitor(), cleanup_memory_monitor(), display_stats(), init_cpu_monitor(), init_disk_monitor(), init_display(), init_gpu_monitor(), init_memory_monitor(), keep_running, sig_handler(), and update_stats().
sig_handler()
void sig_handler (int sig)
Signal handler for clean program termination.
Parameters
sig Signal number
Definition at line 15 of file main.c.
References keep_running.
Referenced by main().
Variable Documentation
keep_running
volatile int keep_running = 1 static
Definition at line 9 of file main.c.
Referenced by main(), and sig_handler().